-- MySQL Script generated by MySQL Workbench
-- Mon Apr  8 12:20:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Clinica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Clinica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Clinica` DEFAULT CHARACTER SET utf8mb3 ;
USE `Clinica` ;

-- -----------------------------------------------------
-- Table `Clinica`.`Credential`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`Credential` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_lastname` VARCHAR(45) NOT NULL,
  `licenseNumber` VARCHAR(45) NOT NULL,
  `especiality` VARCHAR(45) NOT NULL,
  `intitute` VARCHAR(45) NOT NULL,
  `graduationDate` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `licenseNumber_UNIQUE` (`licenseNumber` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Clinica`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(120) NULL DEFAULT NULL,
  `role` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `dateCreated` DATE NOT NULL,
  `dateDeleted` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 140
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Clinica`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`Doctor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `dateCreated` DATE NOT NULL,
  `dateDeleted` DATE NULL DEFAULT NULL,
  `User_id` INT NOT NULL,
  `Credential_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Doctor_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Doctor_Credential1_idx` (`Credential_id` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Credential1`
    FOREIGN KEY (`Credential_id`)
    REFERENCES `Clinica`.`Credential` (`id`),
  CONSTRAINT `fk_Doctor_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `Clinica`.`User` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Clinica`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`Patient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `birthdate` DATE NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `dateCreated` DATE NOT NULL,
  `dateDeleted` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Clinica`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`Appointment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `appintment_Status` VARCHAR(45) NOT NULL,
  `appointment_date` DATE NOT NULL,
  `dateCreated` DATE NOT NULL,
  `dateDeleted` DATE NULL DEFAULT NULL,
  `Patient_id` INT NOT NULL,
  `Doctor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Appointment_Patient1_idx` (`Patient_id` ASC) VISIBLE,
  INDEX `fk_Appointment_Doctor1_idx` (`Doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_Doctor1`
    FOREIGN KEY (`Doctor_id`)
    REFERENCES `Clinica`.`Doctor` (`id`),
  CONSTRAINT `fk_Appointment_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `Clinica`.`Patient` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Clinica`.`Telephone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`Telephone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `areaCod` INT NOT NULL,
  `number` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Clinica`.`Doctor_Telephone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`Doctor_Telephone` (
  `idDoctor_Telephone` INT NOT NULL AUTO_INCREMENT,
  `Telephone_id` INT NOT NULL,
  `Doctor_id` INT NOT NULL,
  PRIMARY KEY (`idDoctor_Telephone`),
  INDEX `fk_Doctor_Telephone_Telephone1_idx` (`Telephone_id` ASC) VISIBLE,
  INDEX `fk_Doctor_Telephone_Doctor1_idx` (`Doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Telephone_Doctor1`
    FOREIGN KEY (`Doctor_id`)
    REFERENCES `Clinica`.`Doctor` (`id`),
  CONSTRAINT `fk_Doctor_Telephone_Telephone1`
    FOREIGN KEY (`Telephone_id`)
    REFERENCES `Clinica`.`Telephone` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Clinica`.`Medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`Medicine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description_Medicine` TEXT NULL DEFAULT NULL,
  `instruction` TEXT NOT NULL,
  `dateCreated` DATE NOT NULL,
  `dateDeleted` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Clinica`.`Prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`Prescription` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prescription_date` DATE NOT NULL,
  `dose` VARCHAR(45) NOT NULL,
  `instruction` TEXT NOT NULL,
  `Medicine_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Prescription_Medicine1_idx` (`Medicine_id` ASC) VISIBLE,
  CONSTRAINT `fk_Prescription_Medicine1`
    FOREIGN KEY (`Medicine_id`)
    REFERENCES `Clinica`.`Medicine` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Clinica`.`Historical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`Historical` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `diagnosis` VARCHAR(45) NOT NULL,
  `treatment` TEXT NOT NULL,
  `recommends` TEXT NOT NULL,
  `result` VARCHAR(100) NOT NULL,
  `Appointment_id` INT NOT NULL,
  `Patient_id` INT NOT NULL,
  `Prescription_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Historical_Appointment1_idx` (`Appointment_id` ASC) VISIBLE,
  INDEX `fk_Historical_Patient1_idx` (`Patient_id` ASC) VISIBLE,
  INDEX `fk_Historical_Prescription1_idx` (`Prescription_id` ASC) VISIBLE,
  CONSTRAINT `fk_Historical_Appointment1`
    FOREIGN KEY (`Appointment_id`)
    REFERENCES `Clinica`.`Appointment` (`id`),
  CONSTRAINT `fk_Historical_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `Clinica`.`Patient` (`id`),
  CONSTRAINT `fk_Historical_Prescription1`
    FOREIGN KEY (`Prescription_id`)
    REFERENCES `Clinica`.`Prescription` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Clinica`.`Patient_Telephone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`Patient_Telephone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Telephone_id` INT NOT NULL,
  `Patient_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_table1_Telephone_idx` (`Telephone_id` ASC) VISIBLE,
  INDEX `fk_table1_Patient1_idx` (`Patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_table1_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `Clinica`.`Patient` (`id`),
  CONSTRAINT `fk_table1_Telephone`
    FOREIGN KEY (`Telephone_id`)
    REFERENCES `Clinica`.`Telephone` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
