- name: Clinica service Instalation
  hosts: nodes
  become: yes
  pre_tasks:
    - name: OS distribution
      set_fact:
        is_Debian: "{{ansible_distribution_file_variety == 'Debian' }}"
        is_Red_Hat: "{{ansible_distribution_file_variety == 'RedHat' }}"
        id_SuSE: "{{ansible_distribution_file_variety == 'SuSE' }}"
        id_Arch: "{{ansible_distribution_file_variety == 'Arch' }}"
  tasks:
    - name: Distribution
      debug:
        msg: "Distribution : {{ansible_distribution_file_variety}}"
    - name: Update cache
      apt:
        update_cache: yes
      when: is_Debian
